const Invoice = require('../models/Invoice');
const Subscription = require('../models/Subscription');
const sendEmail = require('../utils/sendEmail');

// @desc    Get all invoices
const getInvoices = async (req, res) => {
  try {
    const filter = {};
    if (req.user.role === 'portal') {
      filter.customer = req.user._id;
    }
    const invoices = await Invoice.find(filter)
      .populate('customer', 'name email')
      .populate('subscription', 'subscriptionNumber')
      .sort({ createdAt: -1 });
    res.json(invoices);
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

// @desc    Get single invoice
const getInvoice = async (req, res) => {
  try {
    const invoice = await Invoice.findById(req.params.id)
      .populate('customer', 'name email phone')
      .populate('subscription', 'subscriptionNumber plan')
      .populate('lines.product', 'productName');
    if (!invoice) return res.status(404).json({ message: 'Invoice not found' });
    res.json(invoice);
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

// @desc    Create invoice from subscription
const createInvoice = async (req, res) => {
  try {
    const { subscriptionId, dueDate } = req.body;
    const subscription = await Subscription.findById(subscriptionId).populate('customer', 'name email');
    
    if (!subscription) {
      return res.status(404).json({ message: 'Subscription not found' });
    }

    // Build invoice lines from subscription order lines
    const lines = subscription.orderLines.map(line => ({
      product: line.product,
      quantity: line.quantity,
      unitPrice: line.unitPrice,
      taxAmount: line.taxes || 0,
      discountAmount: 0,
      lineTotal: line.amount
    }));

    const subtotal = lines.reduce((sum, l) => sum + (l.unitPrice * l.quantity), 0);
    const totalTax = lines.reduce((sum, l) => sum + l.taxAmount, 0);
    const totalAmount = subtotal + totalTax;

    const invoice = await Invoice.create({
      subscription: subscriptionId,
      customer: subscription.customer,
      dueDate,
      lines,
      subtotal,
      totalTax,
      totalAmount,
      createdBy: req.user._id
    });

    if (subscription.customer && subscription.customer.email) {
      const invoiceUrl = `http://localhost:5173/invoices/${invoice._id}`;
      const htmlTemplate = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 10px; color: #334155;">
          <h2 style="color: #2563eb; margin-top: 0;">New Invoice: ${invoice.invoiceNumber}</h2>
          <p>Hello <strong>${subscription.customer.name}</strong>,</p>
          <p>A new invoice has been generated for your subscription.</p>
          
          <div style="background-color: #f8fafc; padding: 15px; border-left: 4px solid #2563eb; margin: 20px 0;">
            <p style="margin: 0; font-size: 18px;"><strong>Amount Due:</strong> $${invoice.totalAmount.toFixed(2)}</p>
            <p style="margin: 5px 0 0 0;"><strong>Due Date:</strong> ${new Date(invoice.dueDate).toLocaleDateString()}</p>
          </div>
          
          <p>Please log securely into your portal to process payment via Credit Card or Bank Transfer.</p>
          <a href="${invoiceUrl}" style="display: inline-block; background-color: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; margin-top: 10px;">View & Pay Invoice</a>
          
          <hr style="border: 0; border-top: 1px solid #e2e8f0; margin-top: 30px; margin-bottom: 20px;">
          <p style="font-size: 12px; color: #94a3b8; text-align: center;">
            This is an automated billing message generated by your Subscription Management System.
          </p>
        </div>
      `;

      // Fire and forget (don't await so API is fast)
      sendEmail({
        to: subscription.customer.email,
        subject: `Invoice ${invoice.invoiceNumber} is Due`,
        html: htmlTemplate
      }).catch(err => console.error("Email send failed:", err));
    }

    res.status(201).json(invoice);
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

// @desc    Update invoice status
const updateInvoiceStatus = async (req, res) => {
  try {
    const { status } = req.body;
    const validTransitions = {
      draft: ['confirmed', 'cancelled'],
      confirmed: ['paid', 'cancelled'],
      paid: [],
      cancelled: []
    };

    const invoice = await Invoice.findById(req.params.id);
    if (!invoice) return res.status(404).json({ message: 'Invoice not found' });

    if (!validTransitions[invoice.status]?.includes(status)) {
      return res.status(400).json({ 
        message: `Cannot transition from '${invoice.status}' to '${status}'` 
      });
    }

    invoice.status = status;
    await invoice.save();
    res.json(invoice);
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

module.exports = { getInvoices, getInvoice, createInvoice, updateInvoiceStatus };
